home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
urlpatterns=[
        path('',views.index, name='index'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contactus/', views.contactus, name='contactus'),
    path('events/', views.events, name='events'),   
    path('explore/', views.explore, name='explore'),   
    path('items/<int:Items_id>', views.items, name='items'),   
    path('blog/', views.blog, name='blog'),   
    path('posts/<int:Blog_id>', views.posts, name='posts'),   
    path('eventsdetails/<int:Events_id>', views.eventsdetails, name='eventsdetails'),   

]

instrumentRental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    re_path(r'^(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('tinymce',include('tinymce.urls')),
]

home/models.py
from django.db import models
from django.utils import timezone
import shutil
import os
from uuid import uuid4
from django.dispatch import receiver
from django.db.models.signals import post_delete

class ProductsType(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)
    image = models.ImageField(upload_to='products/photos/', null=False)
    upload_path = models.CharField(max_length=255, blank=True, unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk: 
            timestamp = timezone.now().strftime("%Y%m%d%H%M%S")
            self.upload_path = f'products/{self.name}_{timestamp}/'
            upload_path = f'products/{self.name}_{timestamp}/'
            self.image.field.upload_to = upload_path
        super().save(*args, **kwargs)

@receiver(post_delete, sender=ProductsType)
def delete_ProductsType_directory(sender, instance, **kwargs):
    upload_path = 'media/' + instance.upload_path
    try:
        shutil.rmtree(upload_path)
        print(f"Folder {upload_path} successfully deleted.")
    except OSError as e:
        print(f"Error: {upload_path} : {e.strerror}")

class Products(models.Model):
    ProductsType = models.ForeignKey(ProductsType, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100, blank=False, unique=True)
    Price = models.FloatField(null=False)
    image = models.ImageField(upload_to="products/images/", null=False)
    description = models.TextField(null=False)

    def delete(self):
        self.image.delete()
        super().delete()

    def __str__(self):
        return self.Name
    
    def save(self, *args, **kwargs):
        if self.pk:
            old_image = Products.objects.get(pk=self.pk)
            if old_image.image != self.image or old_image.ProductsType != self.ProductsType:
                self.image.field.upload_to = self.ProductsType.upload_path
                if os.path.exists(old_image.image.path):
                    new_image_path = self.ProductsType.upload_path(os.path.basename(old_image.image.path))
                    shutil.move(old_image.image.path, new_image_path)
        else:
            self.image.field.upload_to = self.ProductsType.upload_path
        super().save(*args, **kwargs)

def wrapper(instance, filename):
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext) 
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join('events/to/photos/', filename)    

def newswrapper(instance, filename):
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext) 
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return os.path.join('news/to/photos/', filename)    

class Events(models.Model):
    name = models.CharField(max_length=50, blank=False, unique=True)
    location = models.CharField(max_length=50, blank=False)
    Description = models.TextField(blank=False)
    image = models.ImageField(upload_to=wrapper, null=False)
    Event_Start_Date = models.DateField(default=timezone.now)
    Event_End_Date = models.DateField(default=timezone.now)

    def delete(self):
        self.image.delete()
        super().delete()

    def __str__(self):
        return self.name

class newsBlog(models.Model):
    title = models.CharField(max_length=50, unique=True, null=False)
    description = models.TextField(max_length=200, null=False)
    image = models.ImageField(upload_to=newswrapper, blank=False)
    date = models.DateField(default=timezone.now, editable=False)

    def delete(self):
        self.image.delete()
        super().delete()

    def __str__(self):
        return self.title

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=False)
    message = models.TextField(max_length=250)
    subject = models.TextField(max_length=250)
    created_at = models.DateField(default=timezone.now, editable=False)

    def __str__(self):
        return self.name

class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question

home/forms.py
from django import forms
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from home.models import ContactMessage, newsBlog,Events


class EventForm(forms.ModelForm):
    
    class Meta:
        model=Events
        fields = ('image','Description','name','Event_Start_Date','Event_End_Date')
        widgets={
            "Description":forms.Textarea(attrs={"rows":"4",'cols':'50','placeholder':"Enter Description"}),
             "name":forms.TextInput(attrs= {'placeholder':'Title'}),
             "Event_Start_Date": forms.DateInput(attrs={"type": "date"}),
            "Event_End_Date": forms.DateInput(attrs={"type": "date"}),
        }

class ContactForm(forms.ModelForm):

    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message', 'subject']



class newsForm(forms.ModelForm):
    class Meta:
        model=newsBlog
        fields=('title','description','image')
        widgets={
            "title": forms.TextInput(attrs={'placeholder':'News Title'}),
            "description": forms.Textarea(attrs={"rows":"3","cols":"50",'placeholder':"Write News in Details..."}),
        }

home/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.core.mail import send_mail
from django.core.paginator import Paginator
from home.forms import ContactForm
from home.models import Events, Products, FAQ, newsBlog
from django.utils import timezone

# Create your views here.
def index(request):
    return render(request,'landing_pages/index.html',{})

def aboutus(request):
    return render(request,'landing_pages/about.html',{})

def contactus(request):
    faqdata = FAQ.objects.all()  

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            name = form.cleaned_data['name']
            message_phone_number = form.cleaned_data['contact_Number']
            message_email = form.cleaned_data['email']
            message_message = form.cleaned_data['message']
            
            try:
                send_mail(
                f"Message from: {name}",
                f"{message_message}\nPhone number: {message_phone_number}\nEmail: {message_email}",
                message_email,
                ['grgjeny619@gmail.com'],
                fail_silently=False)
                return JsonResponse({'success': True})

                
            except Exception as e:
                # Handle the exception if the email fails to send
                print(f"Error sending email: {e}")
                return JsonResponse({'success': False, 'errors':e})

        else:
            print(f"Error sending email: {form.errors}")

            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = ContactForm()
        
    return render(request, 'landing_pages/contact.html', {'form': form, 'faqs': faqdata})


def events(request):
    today = timezone.now().date()
    eventsdata = Events.objects.filter(Event_End_Date__gte=today)
    return render(request, 'events/event.html', {'data': eventsdata})


def eventsdetails(request,Events_id):
    eventsdata=get_object_or_404(Events,pk=Events_id)
    return render(request,"events/event-details.html",{'event':eventsdata})


def explore(request):
    p=Paginator(Products.objects.all(),6)
    page=request.GET.get('page')
    Products_List=p.get_page(page)
    nums='a'*Products_List.paginator.num_pages
    return render(request,'explore/explore.html',{'Products_List':Products_List,'nums':nums})

def items(request,Items_id):
    item=get_object_or_404(Products,pk=Items_id)
    return render(request,'explore/details.html',{'item':item})
def blog(request):
    blogsdata=newsBlog.objects.all()
    return render(request,"landing_pages/blog.html",{'data':blogsdata})
def posts(request,Blog_id):
    blogdata= get_object_or_404(newsBlog, pk=Blog_id)
    return render (request,"landing_pages/posts.html",{"posts":blogdata}) 

def login(request):
    return render(request,'login.html',{})

home/templates/landing_pages/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .my-card {
        transition: transform 0.2s ease-in-out;

    }

    .my-card:hover {
        transform: scale(101.9%);
        /* Adjust the scale factor as needed */

    }


    @media (max-width: 576px) {

        .my-card {
            transform: none;
        }

    }
</style>

<div class="text-center bg-image" data-aos="zoom-in-up"
    style="
      background-image: url('{% static 'img\about\blogging-backdrop-8ifwoxtwf7mdg268.jpg' %}'); height: 600px; background-repeat: no-repeat; background-size:cover; margin-top:-100px; opacity:96% ;">

    <div class="d-flex justify-content-center align-items-center h-100">
        <div class="container">
            <div class="row align-items-center justify-content-center">

                <div class="col-md-12">
                    <h1 class=" font-weight-bold"> <strong>Our Blogs</strong></h1>
                    <div class="custom-breadcrumbs">
                        {% comment %} <a href="{% url 'explore:items' %}" style="color: white; text-decoration: none;">Posts</a> {% endcomment %}
                        <span class="mx-2 slash text-light"></span>
                        <span class="text-white"></span>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>

<div class="container mt-0 mx-auto">
    {% include 'messages.html' %}

    <div class="row mt-5 pt-4">
        {% for post in data  %}
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card mb-5 shadow-lg my-card">
                <figure class="card-img-top m-0 overflow-hidden bsb-overlay-hover">
                    <a href="#" style="height:249px;">
                        <img class="img-fluid bsb-scale bsb-hover-scale-up" loading="lazy" src="{{ post.image.url }}"
                            alt="{{ post.title }}" height="236px">
                    </a>
                    <figcaption>
                        <h4 class="h6 text-white bsb-hover-fadeInRight mt-2">Read More</h4>
                    </figcaption>
                </figure>




                <div class="card-body ">
                    <div class="card-title">
                        <h2>{{post.title|truncatewords:3}}</h2>
                    </div>
                    <div class="card-text">
                        <p align="justify">
                            {{post.description|truncatechars:75}}
                        </p>

                    </div>



                </div>
                <div class="card-footer border ">

                    <a href="{% url 'posts' post.pk %}" class="btn btn-danger d-inline m-0">View More</a>
                    <p class="d-inline float-end m-1">
                        {{post.date}}
                    </p>




                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% include 'paginator.html' %}


{%endblock %}

home/templates/landing_pages/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="text-center"  data-aos="zoom-in-up">

    <div class="d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-12">
                <div class="text-center">
                    <h1 class="font-weight-bold">Contact Us</h1>
                    
                </div>
            </div>
        </div>
    </div>
    </div>

</div>

    <div class="container mb-5">
        {% include 'messages.html' %}
        <div class="row align-items-center justify-content-center">
            
            <hr class="hr-heading" />
            <!-- Map section -->
            <div class="col-md-7">

                
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3533.878769267631!2d85.3307661!3d27.712094!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb196de5da5741%3A0x652792640c70ede9!2sHerald%20College%20Kathmandu!5e0!3m2!1sen!2snp!4v1640804481237!5m2!1sen!2snp"
                    width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
            <div class="col-md-5 justify-content-center">
                
                <p class="lead">
                    If you have any questions or inquiries, feel free to reach out to us using the contact information below:
                </p>
            
                <form action="#" method="POST" >
                    {% include 'messages.html' %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}">Name</label>
                        <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}"
                            placeholder="{{ form.name.field.widget.attrs.placeholder }}" >
                    </div>
                    <div class="form-group mt-3">
                        <label for="{{ form.email.id_for_label }}">Email</label>
                        <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}"
                            placeholder="{{ form.email.field.widget.attrs.placeholder }}">
                    </div>
                    <div class="form-group mt-3">
                        <label for="{{ form.subject.id_for_label }}">Subject</label>
                        <input type="text" class="form-control" id="{{ form.subject.id_for_label }}" name="{{ form.subject.name }}"
                            placeholder="{{ form.subject.field.widget.attrs.placeholder }}">
                    </div>
                    <div class="form-group mt-3">
                        <label for="{{ form.message.id_for_label }}">Message</label>
                        <textarea class="form-control" id="{{ form.message.id_for_label }}" name="{{ form.message.name }}"
                            placeholder="{{ form.message.field.widget.attrs.placeholder }}"></textarea>
                    </div>
                    <button type="submit" class="btn btn-dark mt-3" style="margin-left: 40%;" >Send Message</button>
                </form>
            </div>
            
        </div>
    </div>



{%endblock %}

home/templates/landing_pages/dispute.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="text-center bg-image" data-aos="zoom-in-up"
    style="
      background-image: url('{% static 'img/about/aboutus2.jpg' %}'); height: 600px; background-repeat: no-repeat; background-size:cover; margin-top:-100px; opacity:96% ;">

    <div class="d-flex justify-content-center align-items-center h-100">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">
                        <h1 class="text-white font-weight-bold">Dispute</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mb-5">
    {% include 'messages.html' %}
    <div class="row align-items-center justify-content-center">
        <h2 class="mb-4 fw-bold text-center " style="margin-top: 25px;">Get in Touch</h2>

        <hr class="hr-heading" />
        <!-- Map section -->
        <div class="col-md-7">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3533.878769267631!2d85.3307661!3d27.712094!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb196de5da5741%3A0x652792640c70ede9!2sHerald%20College%20Kathmandu!5e0!3m2!1sen!2snp!4v1640804481237!5m2!1sen!2snp"
                width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="col-md-5 justify-content-center">
            <p class="lead">
                If you have any kind of issues, feel free to reach out to us using the dispute form below:
            </p>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Name</label>
                    <input type="text" class="form-control" id="id_name" name="name" placeholder="Your Name">
                </div>
                <div class="form-group mt-3">
                    <label for="id_email">Email</label>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Your Email">
                </div>
                <div class="form-group mt-3">
                    <label for="id_invoice">Invoice</label>
                    <input type="text" class="form-control" id="id_invoice" name="invoice" placeholder="Invoice">
                </div>
                <div class="form-group mt-3">
                    <label for="id_message">Issue</label>
                    <textarea class="form-control" id="id_message" name="issue" placeholder="Your Message"></textarea>
                </div>
                <button type="submit" class="btn btn-dark mt-3" style="margin-left: 40%;">Send Message</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

home/templates/landing_pages/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    @media (max-width: 576px) {
        .carousel-item {
            height: 80vh;
        }
    }
</style>
<section class="hero-carousel">


    <div id="carouselExampleIndicators" class="carousel slide my-carousel" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner" style="margin-top: -100px;">
            <div class="carousel-item active">
                <div class="overlay-image img-fluid">
                    <img src="{% static 'img\piano image.jpg' %}" alt="">
                </div>

                <div class="carousel-caption d-md-block">
                    <h3 class="display-3 w100"><span class="w900">Rent</span> Your <span
                            class="w600 text-secondary">Dream</span>
                        <span class="w900">Instrument</span>
                    </h3>
                    <p>Embrace the Music: Instruments for Every Occasion</p>
                </div>
            </div>
            <div class="carousel-item">
                <div class="overlay-image img-fluid">
                    <img src="{% static 'img\musical instrunment.jpg' %}" alt="">
                </div>
                <div class="carousel-caption d-md-block">
                    <h3 class="display-3 w100"><span class="w900">Events</span><span class="w600 text-secondary">
                            Unplugged</span>
                    </h3>
                    <p>Elevate Your Occasion: Seamless Booking for Memorable Events</p>
                </div>
            </div>
            <div class="carousel-item">
                <div class="overlay-image img-fluid">
                 <img src="{% static 'img/The-Right-Home-Music.jpg' %}" alt="">
                </div>
                <div class="carousel-caption d-md-block">
                    <h3 class="display-3 w100"><span class="w900">Play</span> <span
                            class="w600 text-secondary">Celebrate</span>Repeat
                    </h3>
                    <p>Rent Instruments, Book Events: Your Rhythm, Your Way</p>
                </div>
            </div>


        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>

<section class=" about-us py-3 py-md-5 py-xl-8" data-aos="">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7 col-xxl-6">
                <h2 class="mb-4 display-5 text-center">About Us</h2>
                <p class="text-secondary mb-5 text-center"> Welcome to Instrument Rental, where passion for music meets the art
                    of celebration.</p>
                <hr class="w-50 mx-auto mb-5 mb-xl-9 border-dark-subtle border-2 ">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row gy-3 gy-md-4 gy-lg-0 align-items-lg-center">
            <div class="col-lg-5 col-sm-6 ">

                <img class="img-fluid hover-image" src="{%static 'img\music-background-instrumento-wallpaper-preview.jpg'%}" alt="" height="500px"
                    width="auto">
            </div>



            <div class="col-lg-6 col-sm-12 col-xl-7">
                <div class="row justify-content-xl-center">

                    <h2 class="mb-3">Who Are We?</h2>
                    <p class="lead fs-4 text-secondary mb-3">Welcome to Instrument Rental , your premier destination for
                        musical instrument rentals and event booking. We are a
                        passionate team of music enthusiasts dedicated to bringing the joy of music to every
                        celebration.We help people to Post incredible brands and superior
                        items to rent. Our perspective is to furnish outstanding captivating rental services.</p>
                    <p class="mb-5">
                        Driven by our love for music and the desire to enhance your celebrations, Instrument Rental  is
                        more than just a
                        rental service—it's a gateway to a world where melodies and memories intertwine. Join us in
                        creating soundtracks for
                        your life's most cherished moments.</p>
                    

                </div>

            </div>

        </div>
    </div>
</section>

<section class="mt-3">

    <div id="hot-deal">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-7">
                    <div class="image"
                        style="background: url('{%static 'img\tumblr_mw26odYf521qjrlalo1_500-101.jpg'%}') center center / cover no-repeat; height: 100%;">
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="hot-deal">
                        <ul class="hot-deal-countdown">
                            <li>
                                <div>
                                    <h3>02</h3>
                                    <span>Days</span>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <h3>10</h3>
                                    <span>Hours</span>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <h3>34</h3>
                                    <span>Mins</span>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <h3>60</h3>
                                    <span>Secs</span>
                                </div>
                            </li>
                        </ul>
                        <h2 class="text-uppercase">Discover Packages</h2>
                        <p>New Collection Up to 50% OFF</p>
                        <a class="btn btn-danger" href="#">Rent Now</a>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
</section>





<section class="bg-light py-5 py-xl-6" data-aos="">
    <div class="container mb-5 mb-md-6">
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7 text-center">
                <h2 class="mb-4 display-5">Clients</h2>
                <p class="text-secondary mb-4 mb-md-5">Join the ranks of our satisfied clients who have experienced the
                    magic of music and celebration with us.Here, we take
                    pride in building lasting relationships and creating memorable experiences for all our clients.</p>
                <hr class="w-50 mx-auto mb-0 text-secondary">
            </div>
        </div>
    </div>
    <div class="container overflow-hidden">
        <div class="row gy-5 gy-md-6">
            <div class="col-6 col-sm-3 sm-start-0 align-self-center text-center">

                <img src="{%static 'img/client2.png'%}" alt="" class="img-fluid" width="350" height="155"
                    viewBox="0 0 125 155" fill="currentColor" class="text-dark">
            </div>
            <div class="col-6 col-sm-3 align-self-center text-center">
                <img src="{%static 'img/client1.png'%}" alt="" class="img-fluid" width="200" height="155"
                    viewBox="0 0 125 155" fill="currentColor" class="text-dark">
            </div>
            <div class="col-6 col-sm-3 align-self-center text-center">
                <img src="{%static 'img/client3.png'%}" alt="" class="img-fluid" width="200" height="75"
                    viewBox="0 0 125 155" fill="currentColor" class="text-dark">
            </div>
            <div class="col-6 col-sm-3 align-self-center text-center">
                <img src="{%static 'img/client4.png'%}" alt="" class="img-fluid" width="250" height="155"
                    viewBox="0 0 155 155" fill="currentColor" class="text-dark">

            </div>
        </div>

    </div>
</section>






{%endblock%}

home/templates/landing_pages/pdf_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rental Confirmation</title>
    <style>
        /* Define your CSS styles here */
        body {
            font-family: Arial, sans-serif;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
        }

        h1,
        h2 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Rental Confirmation</h1>
        <p>Hello {{ user.first_name }},</p>
        <p>Your rental has been confirmed. Below are the details:</p>
        <table>
            <tr>
                <th>Item Name</th>
                <td>{{ item.name }}</td>
            </tr>
            <tr>
                <th>Rental Start Date</th>
                <td>{{ Rentitem_Date_of_Booking }}</td>
            </tr>
            <tr>
                <th>Rental End Date</th>
                <td>{{ Rentitem_Date_of_Return }}</td>
            </tr>
            <tr>
                <th>Total Amount</th>
                <td>${{ total_amount }}</td>
            </tr>
            <!-- Add more details as needed -->
        </table>
        <p>Thank you for using our service.</p>
    </div>
</body>

</html>